spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://bgwymeok8trotre9i0nx-mysql.services.clever-cloud.com:3306/bgwymeok8trotre9i0nx?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: urx4pmgigh9x6eq3
    password: rQw8cUim8xZowdXXLwpD
    hikari:
      maximumPoolSize: 100
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

  server:
    port: 3306