spring:
  datasource:
    url: jdbc:sqlserver://tabdatabase.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: tabadmin123
    password: tabhaslo123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

  server:
    port: 3306